<a href="https://colab.research.google.com/github/priteshvermaa/Devops_-_Python/blob/master/Numpy/Numerical_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#**Elementwise Operations**
**1. Basic Operations**

**With scalers**

In [2]:
a = np.array([1, 2, 3, 4]) #create an array

a + 1

array([2, 3, 4, 5])

In [3]:
a ** 2

array([ 1,  4,  9, 16])

**All arithmetic operates elementwise**

In [5]:
b = np.ones(4) + 1
a - b

array([-1.,  0.,  1.,  2.])

In [6]:
a * b

array([2., 4., 6., 8.])

In [8]:
# Matrix multiplication 

c = np.diag([1, 2, 3, 4])
print(c*c)
print("********************")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
********************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [12]:
# comparisons
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
c = np.array([1, 2, 3, 4])
# arraywise comparison
print(np.array_equal(a, b))
print(np.array_equal(a, c))

#elementwise comparioson
print(a == b)
print(a == c)
print(a > b)

False
True
[False  True False  True]
[ True  True  True  True]
[False False  True False]


**Logical Operations**


In [13]:
a = np.array([1, 1, 0, 0], dtype = bool)
b = np.array([1, 0, 1, 0], dtype = bool)

print(np.logical_or(a, b))
print("**********************")
print(np.logical_and(a, b))
print("**********************")


[ True  True  True False]
**********************
[ True False False False]
**********************


**Transcendental functions:**

In [14]:
a = np.arange(5)

np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [15]:
np.log(a)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [16]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

**Shape Mismatch**

In [18]:
a = np.arange(4)
a + np.array([1, 2])

ValueError: ignored

#**Basic Reductions**
**Computing sums**

In [19]:
x = np.array([1, 2, 3, 4])
np.sum(x)

10

In [21]:
#sum by rows and by columns

x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [22]:
x.sum(axis = 0) #columns first dimension

array([3, 3])

In [25]:
x.sum(axis = 1) #rows

array([2, 4])

**Other reductions**

In [26]:
x = np.array([1, 3, 2])
x.min()

1

In [27]:
x.max()

3

In [28]:
x.argmin() #index of minimun element

0

In [29]:
x.argmax() #index of maximum element

1

**Logical Operations**

In [31]:
np.all([True, True, False]) # if all are true it returns true otherwise returns false

False

In [32]:
np.any([True, False, False])

True

In [33]:
#Note : can be used for array comparisonns
a = np.zeros((50, 50))
np.any(a != 0)

False

In [34]:
np.all(a == 0)

True

In [35]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])
((a <= b) & (b <= c)).all()

True

**Statistics**

In [36]:
x = np.array([1, 2, 3, 1])
y = np.array([[1, 2, 3], [5, 6, 1]])
x.mean()

1.75

In [38]:
np.median(x)

1.5

In [39]:
np.median(y, axis= -1) 

array([2., 5.])

In [41]:
x.std() #full population standard deviation

0.82915619758885

In [43]:
# load data into numpy array object
#data = np.loadtxt('poputlation.txt')
import os


In [44]:
os.getcwd()

'/content'

In [48]:
data = np.loadtxt('populations.txt')

In [49]:
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [55]:
year, hares, lynxes, carrots = data.T #colums to variables
print(year)

[1900. 1901. 1902. 1903. 1904. 1905. 1906. 1907. 1908. 1909. 1910. 1911.
 1912. 1913. 1914. 1915. 1916. 1917. 1918. 1919. 1920.]


In [57]:
# The mean population over time
populations = data[:, 1:]
populations

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [58]:
#Sample standard deviations
populations.std(axis = 0)

array([20897.90645809, 16254.59153691,  3322.50622558])

In [61]:
np.argmax(populations, axis = 1) # which species has the highest populations each year?

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2])

#**Broadcasting**
Basic operations on numpy arrays (addtion, etc.) are elementwise

In [66]:
a = np.tile(np.arange(0, 40, 10), (3,1))
print(a)
print("************************")
a = np.tile(np.arange(0, 40, 10), (3,2))
print(a)

a = np.tile(np.arange(0, 40, 10), (3,1))

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
************************
[[ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]]


In [67]:

a = a.T
print(a)

[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [68]:
b = np.array([0, 1 ,2])
b

array([0, 1, 2])

In [69]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [76]:
a = np.arange(0, 40, 10)
a.shape


(4,)

In [78]:
a = a[:, np.newaxis] #adds a new axis -> 2D array
a.shape

(4, 1)

In [79]:
a

array([[ 0],
       [10],
       [20],
       [30]])

In [80]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [81]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a.ravel() # return a contigous flattened array. A 1-D array, containing all the elements

array([1, 2, 3, 4, 5, 6])

In [82]:
a.T #transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [83]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

In [84]:
print(a.shape)
print(a)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [85]:
b = a.ravel()
print(b)

[1 2 3 4 5 6]


In [86]:
b = b.reshape((2, 3))
print(b)

[[1 2 3]
 [4 5 6]]


In [88]:
b[0, 0] = 100
print(b)
print("**********************")
print(a)

[[100   2   3]
 [  4   5   6]]
**********************
[[100   2   3]
 [  4   5   6]]


**Note and Beware: reshape may also return a copy!!:**

In [90]:
a = np.zeros((3, 2))
b = a.T.reshape(3*2)
b[0] = 50
print(b)
print(a) #see here it doesn't changed

[50.  0.  0.  0.  0.  0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


**Adding a dimension**

Indexing with the np.newaxis object allows us to add an axis to an array.

newaxis is used to increase the dimension of the existing array by one more dimension, when used once. Thus,

1D array will become 2D array

2D array will become 3D array

3D array will become 4D and so on


In [91]:
z = np.array([1, 2, 3])
z

array([1, 2, 3])

In [93]:
z[:, np.newaxis]


array([[1],
       [2],
       [3]])

In [94]:
a = np.arange(4*3*2).reshape(4, 3, 2)

In [95]:
a.shape

(4, 3, 2)

In [96]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [97]:
a[0, 2, 1]

5

In [99]:
a = np.arange(4)
a.resize((8,))
a

array([0, 1, 2, 3, 0, 0, 0, 0])

In [102]:
b = a
a.resize((4,)) # take care of this type 

ValueError: ignored

**Sorting Data**

In [108]:
#sorting along an axis
a = np.array([[5, 4, 6], [2, 3, 2]])
b = np.sort(a, axis = 0)
print(a)
print("********along the columns******************")
print(b)
print("********along the rows******************")
b = np.sort(a, axis = 1)
print(b)

[[5 4 6]
 [2 3 2]]
********along the columns******************
[[2 3 2]
 [5 4 6]]
********along the rows******************
[[4 5 6]
 [2 2 3]]


In [109]:
#inplace sort
a.sort(axis = 1)
a

array([[4, 5, 6],
       [2, 2, 3]])

In [111]:
#sorting with fancy indexing
a = np.array([4, 3, 1, 2])
j = np.argsort(a) #position of indeces after sorting
j

array([2, 3, 1, 0])

In [112]:
print(a[j])

[1 2 3 4]
