<a href="https://colab.research.google.com/github/priteshvermaa/Devops_-_Python/blob/master/Numpy/Numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**NumPy Arrays**

**python objects**

1. high-level number objects:integer, floating point.

2. containers: list(costless insertion and append), dictionaries(fast lookup)


**Numpy Provides:**

1. extension package to Python for multi-dimensional arrays

2. closer to hardware (efficiency)
3. designed for scientific computation (convinience)
4. Also known as array oriented computing

In [3]:
import numpy as np
a = np.array([0, 1, 2, 3])
print(a)
print(type(a))
print(np.arange(10))

[0 1 2 3]
<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]


**Why it is useful:** Memory-efficient container that provides fast numerical operations.

In [4]:
#python lists

L = range(1000)
%timeit [i**2 for i in L]

1000 loops, best of 5: 270 µs per loop


In [6]:
a = np.array(1000)
%timeit a**2

The slowest run took 48.03 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 5: 842 ns per loop


#**1. Creating arrays**

**1.1. Manual Construction of arrays**

In [7]:
a = np.array([1, 2, 3, 4])

a

array([1, 2, 3, 4])

In [8]:
#print dimension
a.ndim

1

In [10]:
#shape
a.shape

(4,)

In [12]:
# 2-D, 3-D ...

b  = np.array([[0, 1, 2], [3, 4, 5]])

b

array([[0, 1, 2],
       [3, 4, 5]])

In [13]:
b.ndim

2

In [14]:
b.shape

(2, 3)

In [16]:
len(b) #return the size of the first dimension

2

In [18]:
c = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]]])
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [19]:
c.ndim

3

In [20]:
c.shape

(2, 2, 2)

1-D array -> vector

2-D array -> matrix

(3, 4, 5,....n)-D -> Tensor

**1.2 Function for creating arrays**

In [21]:
#using arange function

# arange is an array-valued of the built-in Python range function

a = np.arange(10) # 0, 1......n-1
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
b = np.arange(1, 10, 2) # (start, end(exclusive), step)
b

array([1, 3, 5, 7, 9])

In [23]:
#using linspace

a = np.linspace(0, 1, 6) #(start, end, number of points)
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [25]:
# common arrays

a = np.ones((3, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
b = np.zeros((3, 3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
c = np.eye(3) # return 2-D array woth ones of the diagonal and zeros (identity matrix)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
d = np.eye(3, 2)
d

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [32]:
#create array using diag function

e = np.diag([1, 2, 3])
e

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [33]:
np.diag(a)

array([1., 1., 1.])

In [34]:
#create array using random

#create an array of the given shape and populate it with random samples from a uniform

a = np.random.rand(4)
a

array([0.42868192, 0.32846611, 0.60124275, 0.58105965])

In [36]:
a = np.random.randn(4)
a

array([ 0.38658528, -0.51071315, -0.7128991 ,  2.01407721])

In [37]:
a = np.arange(10)

a.dtype

dtype('int64')

In [38]:
a = np.arange(10, dtype = 'float64')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [41]:
# The default data type is float for zeros and ones function

a = np.zeros((3, 3))

print(a)
a.dtype

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


dtype('float64')

In [43]:
d = np.array([1+2j, 2+6j]) #complex datatype

print(d)
print(d.dtype)

[1.+2.j 2.+6.j]
complex128


In [45]:
s = np.array(['Ram', 'Rahul', 'Rohan'])

s.dtype

dtype('<U5')

In [46]:
b = np.array([True, False, True, False])

print(b.dtype)

bool


**Each built-in data type has a character code that uniquely identifies it.**

'b' - boolean
'i' - (signed) integer
'u' - unsigned integer
'f' - floating point
'c' - complex-floating point
'm' - timedelta
'M' - datetime
'O' = (Python) objects
'S', 'a' - (byte)-string
'U' - Unicode
'v' - raw data (void)

https://numpy.org/doc/stable/user/basics.types.html

#**3. Indexing and Slicing**
**3.1 Indexing**

The items of an array can be accessed and assigned to the same way as other **Python sequences (eg. List)**

In [47]:
a = np.arange(10)
print(a[4])

4


In [48]:
# Form multidimensional arrays, indexes are tuples of integers:

a = np.diag([1, 2, 3])

print(a[2, 2])

3


In [49]:
a [2, 1] = 44 # assigning value

print(a)

[[ 1  0  0]
 [ 0  2  0]
 [ 0 44  3]]


**3.2 Slicing**

In [50]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
a[1:8:2] #[startIndex: endindex(exclusive) : step]

array([1, 3, 5, 7])

In [61]:
#we can also combine assignment and slicing:
a = np.arange(10)
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [62]:
b = np.arange(5)
print(b)
print(a[5:])
a[5:] = b[::-1] #assigning

a


[0 1 2 3 4]
[10 10 10 10 10]


array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

#**4. Copies and Views**

A slicing operation created a view on the original array, which is just a way of accessing array data. Thus the original array is not copied in memory. You can use np.may_share_memory() to check if two array share same memory

In [63]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
b = a[::2]
b

array([0, 2, 4, 6, 8])

In [65]:
np.shares_memory(a, b)

True

In [68]:
b[0] = 10
a

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [69]:
a #eventhough we modified b, it updated a becuase both shares same memory

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [70]:
a = np.arange(10)

c = a[::2].copy() #force a copy
c

array([0, 2, 4, 6, 8])

In [71]:
np.shares_memory(a, c)

False

In [72]:
c[0] = 10 #changing c won't affect a

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#**5. Fancy Indexing**

NumPy arrays can be indexed with slices, but also with boolean or integer arrays**(masks)**. This method is called **Fancy indexing**. It created copies not views.


**Using Boolean Mask**

In [73]:
a = np.random.randint(0, 20, 15)
a

array([ 9, 12, 16,  1, 12,  0, 13,  8,  0, 12, 14, 19,  0, 10, 17])

In [75]:
mask = (a % 2 == 0)
mask

array([False,  True,  True, False,  True,  True, False,  True,  True,
        True,  True, False,  True,  True, False])

In [76]:
extract_from_a = a[mask]

extract_from_a

array([12, 16, 12,  0,  8,  0, 12, 14,  0, 10])

**Indexing with a mask can be very useful to assign a new value to a sub-array

In [77]:
a[mask] = -1 #it assigns -1 where the value is even
a

array([ 9, -1, -1,  1, -1, -1, 13, -1, -1, -1, -1, 19, -1, -1, 17])

In [78]:
a = np.arange(0, 100, 10)

a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [79]:
a[[2, 3 ,2, 4, 2]]

array([20, 30, 20, 40, 20])

In [80]:
# New values can be assigned
a [[9, 7]] = -200
a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])